/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: shuffleInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "shuffleInfo.pb-c.h"
void   shuffle_info__reorder_info__binary_info__init
                     (ShuffleInfo__ReorderInfo__BinaryInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__BinaryInfo init_value = SHUFFLE_INFO__REORDER_INFO__BINARY_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__layout_info__init
                     (ShuffleInfo__ReorderInfo__LayoutInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__LayoutInfo init_value = SHUFFLE_INFO__REORDER_INFO__LAYOUT_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__fixup_info__fixup_tuple__init
                     (ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple         *message)
{
  static const ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple init_value = SHUFFLE_INFO__REORDER_INFO__FIXUP_INFO__FIXUP_TUPLE__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__fixup_info__init
                     (ShuffleInfo__ReorderInfo__FixupInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__FixupInfo init_value = SHUFFLE_INFO__REORDER_INFO__FIXUP_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__source_info__init
                     (ShuffleInfo__ReorderInfo__SourceInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__SourceInfo init_value = SHUFFLE_INFO__REORDER_INFO__SOURCE_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__init
                     (ShuffleInfo__ReorderInfo         *message)
{
  static const ShuffleInfo__ReorderInfo init_value = SHUFFLE_INFO__REORDER_INFO__INIT;
  *message = init_value;
}
size_t shuffle_info__reorder_info__get_packed_size
                     (const ShuffleInfo__ReorderInfo *message)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t shuffle_info__reorder_info__pack
                     (const ShuffleInfo__ReorderInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t shuffle_info__reorder_info__pack_to_buffer
                     (const ShuffleInfo__ReorderInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShuffleInfo__ReorderInfo *
       shuffle_info__reorder_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShuffleInfo__ReorderInfo *)
     protobuf_c_message_unpack (&shuffle_info__reorder_info__descriptor,
                                allocator, len, data);
}
void   shuffle_info__reorder_info__free_unpacked
                     (ShuffleInfo__ReorderInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__binary_info__field_descriptors[4] =
{
  {
    "rand_obj_offset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, has_rand_obj_offset),
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, rand_obj_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "main_addr_offset",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, has_main_addr_offset),
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, main_addr_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obj_sz",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, has_obj_sz),
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, obj_sz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, has_src_type),
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, src_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__binary_info__field_indices_by_name[] = {
  1,   /* field[1] = main_addr_offset */
  2,   /* field[2] = obj_sz */
  0,   /* field[0] = rand_obj_offset */
  3,   /* field[3] = src_type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__binary_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__binary_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.BinaryInfo",
  "BinaryInfo",
  "ShuffleInfo__ReorderInfo__BinaryInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__BinaryInfo),
  4,
  shuffle_info__reorder_info__binary_info__field_descriptors,
  shuffle_info__reorder_info__binary_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__binary_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__binary_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t shuffle_info__reorder_info__layout_info__assemble_type__default_value = 0u;
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__layout_info__field_descriptors[8] =
{
  {
    "bb_size",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_bb_size),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, bb_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_type),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_fixups",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_num_fixups),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, num_fixups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bb_fallthrough",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_bb_fallthrough),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, bb_fallthrough),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, section_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_offset),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "padding_size",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_padding_size),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, padding_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assemble_type",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_assemble_type),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, assemble_type),
    NULL,
    &shuffle_info__reorder_info__layout_info__assemble_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__layout_info__field_indices_by_name[] = {
  7,   /* field[7] = assemble_type */
  3,   /* field[3] = bb_fallthrough */
  0,   /* field[0] = bb_size */
  2,   /* field[2] = num_fixups */
  5,   /* field[5] = offset */
  6,   /* field[6] = padding_size */
  4,   /* field[4] = section_name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__layout_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__layout_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.LayoutInfo",
  "LayoutInfo",
  "ShuffleInfo__ReorderInfo__LayoutInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__LayoutInfo),
  8,
  shuffle_info__reorder_info__layout_info__field_descriptors,
  shuffle_info__reorder_info__layout_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__layout_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__layout_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__fixup_info__fixup_tuple__field_descriptors[7] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deref_sz",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, deref_sz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_rela",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, is_rela),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_type),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, section_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_jt_entries",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_num_jt_entries),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, num_jt_entries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jt_entry_sz",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_jt_entry_sz),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, jt_entry_sz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__fixup_info__fixup_tuple__field_indices_by_name[] = {
  1,   /* field[1] = deref_sz */
  2,   /* field[2] = is_rela */
  6,   /* field[6] = jt_entry_sz */
  5,   /* field[5] = num_jt_entries */
  0,   /* field[0] = offset */
  4,   /* field[4] = section_name */
  3,   /* field[3] = type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__fixup_info__fixup_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple",
  "FixupTuple",
  "ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple),
  7,
  shuffle_info__reorder_info__fixup_info__fixup_tuple__field_descriptors,
  shuffle_info__reorder_info__fixup_info__fixup_tuple__field_indices_by_name,
  1,  shuffle_info__reorder_info__fixup_info__fixup_tuple__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__fixup_info__fixup_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__fixup_info__field_descriptors[5] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_text),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, text),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rodata",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_rodata),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, rodata),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_data),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, data),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datarel",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_datarel),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, datarel),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initarray",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_initarray),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, initarray),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__fixup_info__field_indices_by_name[] = {
  2,   /* field[2] = data */
  3,   /* field[3] = datarel */
  4,   /* field[4] = initarray */
  1,   /* field[1] = rodata */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange shuffle_info__reorder_info__fixup_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__fixup_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.FixupInfo",
  "FixupInfo",
  "ShuffleInfo__ReorderInfo__FixupInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__FixupInfo),
  5,
  shuffle_info__reorder_info__fixup_info__field_descriptors,
  shuffle_info__reorder_info__fixup_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__fixup_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__fixup_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__source_info__field_descriptors[1] =
{
  {
    "src_type",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__SourceInfo, n_src_type),
    offsetof(ShuffleInfo__ReorderInfo__SourceInfo, src_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__source_info__field_indices_by_name[] = {
  0,   /* field[0] = src_type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__source_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__source_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.SourceInfo",
  "SourceInfo",
  "ShuffleInfo__ReorderInfo__SourceInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__SourceInfo),
  1,
  shuffle_info__reorder_info__source_info__field_descriptors,
  shuffle_info__reorder_info__source_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__source_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__source_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__field_descriptors[4] =
{
  {
    "bin",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo, bin),
    &shuffle_info__reorder_info__binary_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "layout",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo, n_layout),
    offsetof(ShuffleInfo__ReorderInfo, layout),
    &shuffle_info__reorder_info__layout_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixup",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo, n_fixup),
    offsetof(ShuffleInfo__ReorderInfo, fixup),
    &shuffle_info__reorder_info__fixup_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo, source),
    &shuffle_info__reorder_info__source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__field_indices_by_name[] = {
  0,   /* field[0] = bin */
  2,   /* field[2] = fixup */
  1,   /* field[1] = layout */
  3,   /* field[3] = source */
};
static const ProtobufCIntRange shuffle_info__reorder_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo",
  "ReorderInfo",
  "ShuffleInfo__ReorderInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo),
  4,
  shuffle_info__reorder_info__field_descriptors,
  shuffle_info__reorder_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
